name: "floor"

createVisualShape:
  shapeType: "GEOM_PLANE"
  planeNormal: [0, 0, 1]

createCollisionShape:
  shapeType: "GEOM_PLANE"
  planeNormal: [0, 0, 1]

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  # restitution: 0.9
  # linearDamping: 0.04
  # angularDamping: 0.04
  # contactStiffness: 2000.0
  # contactDamping: 0.7

object_tf:
  tf_id: "rpbi/floor"
