name: "kuka_lwr"

loadURDF:
  fileName: "{rpbi_examples}/robots/kuka_lwr.urdf"
  useFixedBase: 1
  basePosition: [0.5, 0., 0.]  # can also specify offset in object_tf

initial_joint_position:
  lwr_arm_0_joint: 0.0
  lwr_arm_1_joint: -30.0
  lwr_arm_2_joint: 0.0
  lwr_arm_3_joint: -90.0
  lwr_arm_4_joint: 0.0
  lwr_arm_5_joint: 30.0
  lwr_arm_6_joint: 0.0

is_visual_robot: false

setJointMotorControlArray:
  controlMode: "VELOCITY_CONTROL"

publish_joint_state_frequency: 30

publish_link_states: false
