#
# PyBullet KUKA configuration file
#

urdf_file_name: "/robots/kuka_lwr_force/kuka.urdf"
end_effector: "end_effector_sponge"
use_fixed_base: True
base_position: [0.0, 0.0, 0.0]
base_orient_mat: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
# base_orient_mat: [[0.0, 0.0, -1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]] # rotate around Y 90
# base_orient_mat: [[1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]]  # rotate around X 90
init_position: [0.0, 0.5, 0.3, -0.5, 0.2, 0.8, 0.0]

sensors:

  #
  # You can have multiple sensors on the robot, each attribute label should be
  # specified as follows
  #
  #     SENSOR_TYPE__LABEL
  #
  # where SENSOR_TYPE is one of the following
  #
  #  - joint_force_torque_sensor
  #
  # and LABEL is some unique label. Each sensor type requires certain arguments
  # to be set, see below.
  #
  #  - joint_force_torque_sensor
  #    - joint_index (int, joint index where F/T sensor is attached on the robot)
  #
  # If the robot has no additional sensors then do not specify the sensors
  # attribute.

  joint_force_torque_sensor__end_effector:
    joint_index: 8
