
urdf: '{ros_pybullet_interface}/objects/target_folder/target.urdf'

file_name: ''

name: 'target'

# Basic parameters
mesh_scale:
rgba_color:
base_mass:

# Dynamic parameters
lateral_friction: 0.005
spinning_friction: 0.00
rolling_friction: 0.0
restitution: 0.1
linear_damping: 0.04
angular_damping: 0.04
contact_stiffness: 2000.0
contact_damping: 10.7
localInertiaDiagonal: [0.0125, 0.0125, 0.075]

link_state:

  # Specifying the link state
  #
  # You can set the collision object to be static or dynamic.
  #
  # state collision object
  #   You must specify here a position attribute and orientation attribute.
  #
  # dynamic object
  #
  #   You must specify an attribute tf_frame_id. The position/orientation of the
  #   collision object in PyBullet will be updated according to the
  #   position/orientation of the respective tf frame. In ROS, you must ensure
  #   that this frame can be defined wrt the PyBullet world frame. The PyBullet
  #   world frame is called 'ros_pybullet_interface/world'.
  #
  position: [0, -0.6, 0.3]
  orientation_eulerXYZ: [0.0, 0.0, 0.0]
  # tf_frame_id: "ros_pybullet_interface/target"
