#
# PyBullet KUKA configuration file
#
name: "yang"
file_name: "{ros_pybullet_interface}/robots/kuka_iiwa/iiwa14.urdf"
end_effector: "end_effector_sponge"
use_fixed_base: True
base_position: [-1.24, 0.5, 0.0]
base_orient_eulerXYZ: [0.0, 0.0, -15.0]
# init_position: [0.0, -30., 0., -80., 0., 10., 90.]
# init_position: [-20., 100., 30., 70., 0., 20., 0.]

# init_position: [-160., -95., 45., -60., -35., 20., 90.]

init_position: [ -160., -95., 25., -75., -35., 30., 90.]

#---remounting
#base_position: [1.1, 0.1, 0.0]
#base_orient_eulerXYZ: [0.0, -30.0, 0.0]
#init_position: [0.0, 45., 0., 80., 0., -10., 90.]

sensors:

  #
  # You can have multiple sensors on the robot, each attribute label should be
  # specified as follows
  #
  #     SENSOR_TYPE__LABEL
  #
  # where SENSOR_TYPE is one of the following
  #
  #  - joint_force_torque_sensor
  #
  # and LABEL is some unique label. Each sensor type requires certain arguments
  # to be set, see below.
  #
  #  - joint_force_torque_sensor
  #    - joint_index (int, joint index where F/T sensor is attached on the robot)
  #
  # If the robot has no additional sensors then do not specify the sensors
  # attribute.

  joint_force_torque_sensor__end_effector:
    joint_index: 8


IK:
  # 0-3 orienation, 3-6 position, 0-6 both orienation and position
  # first index in IK
  f_indx : 0
  # last index in IK
  l_indx : 6

  # weights for orientation tracking - [x, y, z] of the target
  # select: at least two of the axes have to be 1
  ori_axis_weights: [1, 1, 1]

  # scaling parameter between orientation and position
  scale_pos_orient : 1.0

  # parameters of the nullspace motion
  alpha_null : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # activation per joint
  h_delta : [0., 0., -0., -0., 0., 0., 0.]     # nominal configuration, aimed via nullspace motion
  h_norm : [340., 240., 340., 240., 340., 240., 350.]  # normalization of the error for each joint (IIWA specific)
