motion_dimensions:
  number: 7

  trans:
    translation_x:
    translation_x_index: 0
    translation_y:
    translation_y_index: 1
    translation_z:
    translation_z_index: 2

  #  'quat' and [3,7] for quaternion, 'euler' and [3,6] for euler angles
  rotation:
    rotation_repr: 'quat'
    rotation_vec:
    rotation_angle:
    rotation_vec_index: [3, 7]


interpolation:
  nochange_window_length: 1
  use_interpolation: True
  inter_dt: 0.01

communication:
  publisher:
    header_frame_id: 'rpbi/kuka_lwr/lwr_arm_0_link'
    msg_child_frame_id: 'interpol_target'
